apiVersion: apps/v1
kind: Deployment
metadata:
  name: liz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liz
  template:
    metadata:
      labels:
        app: liz
    spec:
      containers:
      - image: okteto.dev/liz:latest
        name: liz
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "16f0ed12-87f3-4da6-88c6-db4078a4f2ee"
        - name: Vless_Path
          value: "/ls28s7"
        - name: Vmess_UUID
          value: "16f0ed12-87f3-4da6-88c6-db4078a4f2ee"
        - name: Vmess_Path
          value: "/ms37x5"
        - name: Share_Path
          value: "/v2link"
